name: Simulator Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main

jobs:
  unit_tests:
      runs-on: ubuntu-latest
      strategy:
          matrix:
              cfg:
                  - { BUILD_TYPE: Release }
      steps:
        - uses: actions/checkout@v4
        
        - name: unit tests
          run: |
              cmake -Ssimulator/tests -Bbuild/simulator/test 
              cmake --build build/simulator/test
              ctest --test-dir build/simulator/test --output-on-failure
