name: Style

on:
    pull_request:
        types: [opened, synchronize, reopened]
    
    push:
        branches:
          - main

jobs:
  style_checking:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install format dependencies
      run: pip3 install clang-format==14.0.6 cmake_format==0.6.13 pyyaml

    - name: configure
      run: cmake -Stests/style -Bbuild/style 

    - name: check style
      run: cmake --build build/style --target check-format
