name: Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main

jobs:
    run_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                cfg:
                    - { BUILD_TYPE: Release }
        steps:
          - uses: actions/checkout@v4
          - name: Test
            run: |
                cmake -S. -Bbuild/test
                cmake --build build/test
                ctest --output-on-failure
