name: Library Test
on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main

jobs:
  unit_tests:
      name: Run unit-tests on ${{ matrix.os }} in ${{ matrix.BUILD_TYPE }} mode
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
              BUILD_TYPE: [Release]
              os: [ubuntu-latest, windows-latest, macos-latest]
      steps:
        - uses: actions/checkout@v4
        
        - name: unit tests
          run: |
              cmake -Stests/unit -Bbuild/test 
              cmake --build build/test
              ctest --test-dir build/test --output-on-failure
